pub mod fetch_files;
pub mod rename_files;
pub mod compress_image;
pub mod img_compressors;
pub mod convert_image;
pub mod get_default_browser;
pub mod yt_url_data;
pub mod download_yt_videos;
pub mod resize_image;
